### ISSUE TITLE
Saving belongsTo() relationship doesn't work

### ISSUE THREAD

**Issue by andreyfel** [poteto/ember-changeset#403]
## Version
ember-changeset@^3.0.0-beta.9

## Test Case

Profile model:
```
class Profile extends Model {
  @attr('string') name;
}
```

User model:
```
class User extends Model {
  @attr('string') email;
  @belongsTo('profile') profile;
}
```

Creating a user with a profile and saving it:
```
const profiles = await this.store.finsAll('profile');
const user = this.store.createRecord('user');
const changeset = new Changeset(user, ...);
changeset.set('email', 'example@email.com');
changeset.set('profile', profile[0]);
changeset.save();
```

## Expected Behavior
User is saved

## Actual Behavior
An exception is thrown:
```
Uncaught (in promise) Error: Assertion Failed: Cannot call set with 'name' on an undefined object.
    at assert (index.js:128)
    at _set2 (index.js:2632)
    at setPath (index.js:2692)
    at Object._set2 [as safeSet] (index.js:2642)
    at merge-deep.js:92
    at Array.forEach (<anonymous>)
    at mergeTargetAndSource (merge-deep.js:81)
    at mergeDeep (merge-deep.js:150)
    at Proxy.execute (index.js:196)
    at Proxy._callee$ (validated-changeset.js:261)
```

**Comment by andreyfel** [comment]
Changeset contains ember model in the profile field and apparently it tries to make a deep copy of it on save.

**Comment by andreyfel** [comment]
I've modified one test to illustrate the issue in the testuite: #405 
```
Error: Assertion Failed: Cannot delegate set('firstName', Grace) to the 'content' property of object proxy <(unknown):ember183>: its 'content' is undefined.
    at assert (http://localhost:7357/assets/vendor.js:38210:15)
    at Proxy.setUnknownProperty (http://localhost:7357/assets/vendor.js:27561:48)
    at set (http://localhost:7357/assets/vendor.js:17273:11)
    at setPath (http://localhost:7357/assets/vendor.js:17301:14)
    at Object.set [as safeSet] (http://localhost:7357/assets/vendor.js:17248:14)
    at http://localhost:7357/assets/vendor.js:67256:23
    at Array.forEach (<anonymous>)
    at mergeTargetAndSource (http://localhost:7357/assets/vendor.js:67245:21)
    at mergeDeep (http://localhost:7357/assets/vendor.js:67312:14)
    at Proxy.execute (http://localhost:7357/assets/vendor.js:66796:48)
```

**Comment by snewcomer** [comment]
@andreyfel ref #406 Did this PR fix the issue you were looking at?  3.0.0-beta.10

**Comment by andreyfel** [comment]
@snewcomer I rebased my failing test branch and it still fails.
I think I found an issue, will submit a PR tomorrow.

**Comment by snewcomer** [comment]
@andreyfel Mind checking out the latest release and let me know if this is fixed!?!

**Comment by andreyfel** [comment]
Seems it is no longer an issue with the latest build! Thanks a lot @snewcomer!
