### ISSUE TITLE
Stacklevel too deep during deepMerge (when calling changeset.unexecute())

### ISSUE THREAD

**Issue by sly7-7** [poteto/ember-changeset#652]
## Version

ember-changeset@4.1.0

## Actual Behavior

 It seems like ember-changeset should work well with Ember-Data, but I think I do somehting wrong, because it crashes during `unexecute`, when it encounters a belongsTo relation.   

```Error: Unable to 'mergeDeep' with your data. Are you trying to merge two ember-data objects? Please file an issue with ember-changeset.
    at Proxy.mergeDeep (merge-deep.js:161:1)
    at Proxy.unexecute (validated-changeset.es5.js:409:155)
``` 
but I don't do any merge by myself

**Comment by SergeAstapov** [comment]
@sly7-7 FYI there is related PR #645 which fixes working with Ember Data (there are at least several ways of doing so, that PR suggest one way of doing it).

**Comment by sly7-7** [comment]
@SergeAstapov Hi, thank you for taking time to answer. Unless I'm missing something, my use case is different, as I don't use snapshot/restore, but execute/unexecute. That said, I've tried to run against the PR branch you mentioned, and I have the same "buggy" behavior. I think something wrong happen when `execute`ing changes to the model (this works fine during deep merge), but when `unexecute`ing, it tries to deepmerge two ember-data models (even cloning the underlying backburner instance), but I don't know why.
